deployment:
  name: Deployment
  runs-on: [ %RUNS_ON% ]
  needs: [ promote ]
  steps:
    - name: 'Artifact: download'
      uses: actions/download-artifact@v2
      with:
        name: version-artifact
    - name: 'Shell: set env'
      run: export DOCKER_IMAGE_TAG=$(cat version)
    - name: 'Shell: deployment'
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '%BRANCH_NAME%-workflow.yml',
              ref: context.ref,
              inputs: {
                VERSION: "$VERSION"
              }
          });
