deployment:
  name: '%JOB_NAME%'
  runs-on: [ %RUNS_ON% ]
  needs: [ %NEEDS% ]
  if: ${{ always() }}
  env:
    DEPLOYMENT_REPOSITORY: %DEPLOYMENT_REPOSITORY%
    REPO_ACCESS_TOKEN: %REPO_ACCESS_TOKEN%
  steps:
    - name: Trigger deployment workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: '%WORKFLOW%'
        repo: ${{ env.DEPLOYMENT_REPOSITORY }}
        token: ${{ env.REPO_ACCESS_TOKEN }}
        ref: master
        inputs: '{ "version": "${{ env.VERSION }}" }'
