############## Created by de.microtema:github-workflow-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Files under .github/workflows folder are generated and should not be edited. #
################################################################################

name: '%PIPELINE_NAME%'

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Helm Version'
        default: '1'

  %ENV%

jobs:
  %JOBS%
