########################## Copyright (c) 2020 Microtema ########################
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Files under .github/workflows folder are generated and should not be edited. #
################################################################################

name: '%PIPELINE_NAME%'

on:
  push:
    branches:
      - %BRANCH_NAME%

  %ENV%

jobs:
  %JOBS%
