deployment:
  name: Deployment
  runs-on: [ self-hosted ]
  needs: [ packaging ]
  env:
    TF_CLI_ARGS: "-input=false"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: %AWS_REGION%
        aws-access-key-id: %AWS_ACCESS_KEY_ID%
        aws-secret-access-key: %AWS_SECRET_ACCESS_KEY%
    - name: Terraform Apply
      working-directory: %WORKING_DIRECTORY%
      run: terraform apply tfplan
