name: GitHub Workflows Maven-Plugin [dev]

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  DOCKER_REGISTRY: "docker.registry.local"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  SONAR_TOKEN: "d44e1870f40de9c4556bb1f507393396721e21aa"
  JAVA_VERSION: "17"
  MAVEN_CLI_OPTS: "--ntp --batch-mode --errors --fail-at-end --show-version\
    \ -DinstallAtEnd=true -DdeployAtEnd=true"

jobs:

  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    needs: [ ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Java: Setup'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - name: 'Maven: package'
        run: mvn install -Dcode.coverage=0.0 -DskipTests=true $MAVEN_CLI_OPTS

  publish-github:
    name: Publish to Maven Registry
    runs-on: [ ubuntu-latest ]
    needs: [ build ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Java: Setup'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - name: 'Maven: deploy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy -P release -DskipTests $MAVEN_CLI_OPTS

  publish:
    name: Publish to Maven Central
    runs-on: [ ubuntu-latest ]
    needs: [ build ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Java: Setup'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
          server-id: oss.sonatype.org
          server-username: 7fate@web.de
          server-password: 3t0b1c0k3
          gpg-private-key: 3t0b1c0k3
          gpg-passphrase: 3t0b1c0k3
      - name: 'Maven: deploy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy -P release -DskipTests $MAVEN_CLI_OPTS
